build:
    tests:
        override:
            -
                command: 'phpunit ./tests --coverage-clover=coverage'
                coverage:
                    file: 'coverage'
                    format: 'clover'
